apiVersion: apps/v1
kind: Deployment
metadata:
  name: le-export
spec:
  replicas: 1
  selector:
    matchLabels:
      app: le-export
  template:
    metadata:
      labels:
        app: le-export
    spec:
      containers:
        - name: app
          image: 510806945511.dkr.ecr.us-east-1.amazonaws.com/le-export:aaf28a4f989bacff8a0606d1156dab7f2789e57a
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: NODE_ENV
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: POSTGRES_DATABASE
            - name: POSTGRES_HOST
              valueFrom:
              secretKeyRef:
                name: my-secrets
                key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: POSTGRES_PASSWORD
            - name: EXPORT_BUCKET
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: EXPORT_BUCKET
            - name: SENTRY_URL
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SENTRY_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: le-export-service
spec:
  selector:
    app: le-export
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32193
  type: NodePort
